### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by shadowTW** [Androz2091/minecraft-discord-bot#4]
the codes are not working anymore

**Comment by Androz2091** [comment]
Do you have any error?

**Comment by shadowTW** [comment]
yes, wait a second

**Comment by shadowTW** [comment]
![Uploading Screenshot_20210201-175239_Termux.jpg…]()

**Comment by shadowTW** [comment]
![Screenshot_20210201-175758_Discord](https://user-images.githubusercontent.com/64441627/106491417-23f53f80-64b7-11eb-83cf-61d95f313343.jpg)

**Comment by shadowTW** [comment]
![Screenshot_20210201-175239_Termux](https://user-images.githubusercontent.com/64441627/106491472-2fe10180-64b7-11eb-9004-fe5b3e486801.jpg)

**Comment by Androz2091** [comment]
Looks like the channel ID defined in the config file is incorrect

**Comment by shadowTW** [comment]
![Screenshot_20210201-182251_Chrome](https://user-images.githubusercontent.com/64441627/106494323-9287cc80-64ba-11eb-9b33-e23464e9bccd.jpg)

**Comment by shadowTW** [comment]
![Screenshot_20210201-190145_Chrome](https://user-images.githubusercontent.com/64441627/106498751-fd87d200-64bf-11eb-8b24-4da144d03b90.jpg)

**Comment by Androz2091** [comment]
it's updated
